nginx:
  build: ./nginx
  ports:
    - "80:80"
  links:
    - "php"
  volumes:
    - /var/www:/var/www

php:
  build: ./php
  ports:
    - "9000:9000"
  links:
    - "mysql"
  volumes:
    - /var/www:/var/www

mysql:
  build: ./mysql
  ports:
    - "3306:3306"
  volumes:
    - /var/www/data/mysql:/var/lib/mysql
  environment:
    MYSQL_ROOT_PASSWORD: 123456

